workflows:
  sample-workflow:
    name: Codemagic Sonar Sample
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - github
        - sonar
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
      cancel_previous_builds: true
    artifacts:
      - app/build/outputs/bundle/**/*.aab
    scripts:
      - name: Sonar Analyze
        script: ./gradlew sonarqube
        test_report: app/build/test-results/testDebugUnitTest/*.xml
        ignore_failure: false
      - name: Build Android app
        script: ./gradlew assembleRelease
